### ISSUE TITLE
Help with Video header

### ISSUE THREAD

**Issue by nsalem152** [godaddy-wordpress/primer-child-ascension#88]
I’m having trouble figuring out how to fix my video header on my WordPress homepage. I am using the Ascension theme, Version: 1.1.0 By GoDaddy. My video is embedded from Youtube and will not resize correctly with different screen sizes or for mobile viewing. Black bars appear on top and bottom of header in smaller viewing sizes. Can you please kindly give any advice or help on how I may be able to resolve this issue? I would greatly appreciate it. I have also tried to upload the video, but I wasn’t able to get it to fit or respond correctly either. My URL is:
http://www.winwinproducts.com/dev/
Thank you!

**Comment by GodelMachine** [comment]
I think you need to write some CSS code and mention the dimensions. You may add this CSS code in Additional CSS.

**Comment by EvanHerman** [comment]
Hi @nsalem152 

You can try adding the following CSS to your theme to tweak things a bit:

```css
#wp-custom-header {
   top: 0;
}

#wp-custom-header iframe {
   height: 100%;
}
```

However you may find black bars on the video as you scale down due to the way YouTube video embeds respond.

Evan

**Comment by nsalem152** [comment]
Hi Evan,
Thank you so much for the additional CSS! I had to tweak it a little, and It works until it scales down to mobile view, then I see the black bar again. Earlier, I had also tried instead to uploaded a few videos, but they do not fit and appear too big even though they are the recommended file type and dimensions. Any ideas on how I may be able to get an uploaded video to fit correctly in this video header? I appreciate your feedback. Thank you.

**Comment by EvanHerman** [comment]
It looks like it's just going to need some CSS tweaking. I'll need to loop around and spend some time figuring out what might need to be done.

**Comment by nsalem152** [comment]
Thank you!

**Comment by jamesclaymon** [comment]
Hi there, can you please help with how I can customize the height of the video header.  Thank you

**Comment by EvanHerman** [comment]
@jamesclaymon You can customize the height of the video container using CSS:

```css
.site-header.video-header {
   height: 1000px;
}
```

**Comment by aledesma-godaddy** [comment]
Closing issues and PRs in preparation for repository archival
